In [4]:
weekly_temp = [25,27,28,29,30,31,32]
print("weekly temperature is", weekly_temp)
        

weekly temperature is [25, 27, 28, 29, 30, 31, 32]


In [7]:
city_data = {
    "city": "Bangalore",
    "temperature": 25,
    "humidity": 50,
    "wind_speed": 10,
    "carbon_footprint": 500.75,
    "is_sustainable": "false"
   
}
print(city_data)






{'city': 'Bangalore', 'temperature': 25, 'humidity': 50, 'wind_speed': 10, 'carbon_footprint': 500.75, 'is_sustainable': 'false,'}


In [8]:
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

In [9]:
threshold_temperature = 26 
high_temp_cities = []

for city in climate_data:
    if city["temperature"] > threshold_temperature:
        high_temp_cities.append(city["city"])

print("Cities with temperature above threshold:", high_temp_cities)



Cities with temperature above threshold: ['City B', 'City E']


In [1]:
class Carbon_tracker:
    def __init__(self, transport_mode, distance):
        self.transport_mode = transport_mode
        self.distance = distance
    def calculate_emission(self):
        emission_factor = {"car":0.21, "bus":0.18,"cycle":0.00, "walk":0.0}
        return self.distance * emission_factor.get(self.transport_mode, 0.15)
    def alternative(self):
        if self.transport_mode == "car":
            return "Emission proced by car is more so us is the best alternative"
        elif self.transport_mode == "bus":
            return "Great choice public " 
tracker = Carbon_tracker("car", 35)
tracker1 = Carbon_tracker("bus", 105)
print(f"Emissions: {tracker.calculate_emission()} kg CO2")
print(f"Emissions: {tracker1.calculate_emission()} kg CO2")

Emissions: 7.35 kg CO2
Emissions: 18.9 kg CO2


In [4]:
class EnergySystems:
    def __init__(self, building_name, emission_fac, energy_cons):
        self.building_name = building_name
        self.emission_fac = emission_fac
        self.energy_cons = energy_cons

    def calculate_cf(self):
        return self.emission_fac * self.energy_cons

# Create an instance
A = EnergySystems("Building A", 0.28, 105)

# Print the details and carbon footprint
print(A.building_name, A.emission_fac, A.energy_cons)
print(f"Carbon Footprint: {A.calculate_cf():.2f} kg CO2")

Building A 0.28 105
Carbon Footprint: 29.40 kg CO2


In [5]:
class Waste:
    def __init__(self, weight_kg, category):
        self.weight_kg = weight_kg
        self.category = category
    
    def get_weight(self):
        return self.weight_kg
    
    def get_category(self):
        return self.category

class PlasticWaste(Waste):
    def __init__(self, weight_kg, category, type_of_plastic):
        super().__init__(weight_kg, category)
        self.type_of_plastic = type_of_plastic
    
    def get_plastic_type(self):
        return self.type_of_plastic
    
    def is_recyclable(self):
        recyclable_types = ['PET', 'HDPE', 'PVC', 'LDPE', 'PP', 'PS']
        return self.type_of_plastic in recyclable_types


if __name__ == "__main__":
   
    general_waste = Waste(5.0, "biodegradable")
    print(f"General Waste - Weight: {general_waste.get_weight()}kg, Category: {general_waste.get_category()}")
    
  
    plastic_bottle = PlasticWaste(0.5, "recyclable", "PET")
    print(f"\nPlastic Waste - Weight: {plastic_bottle.get_weight()}kg")
    print(f"Category: {plastic_bottle.get_category()}")
    print(f"Type of Plastic: {plastic_bottle.get_plastic_type()}")
    print(f"Is Recyclable: {plastic_bottle.is_recyclable()}")
    
   
    plastic_bag = PlasticWaste(0.1, "non-recyclable", "OTHER")
    print(f"\nPlastic Waste - Weight: {plastic_bag.get_weight()}kg")
    print(f"Category: {plastic_bag.get_category()}")
    print(f"Type of Plastic: {plastic_bag.get_plastic_type()}")
    print(f"Is Recyclable: {plastic_bag.is_recyclable()}")

General Waste - Weight: 5.0kg, Category: biodegradable

Plastic Waste - Weight: 0.5kg
Category: recyclable
Type of Plastic: PET
Is Recyclable: True

Plastic Waste - Weight: 0.1kg
Category: non-recyclable
Type of Plastic: OTHER
Is Recyclable: False


In [6]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
array = np.array([1,2,3,4,5])
print(array)


[1 2 3 4 5]


In [ ]:
array.ndim

1

In [9]:

matrix1 = [
    [1, 2, 3],
    [4, 5, 6]
]


rows = 2
cols = 3
matrix2 = [[0 for j in range(cols)] for i in range(rows)]


import numpy as np
matrix3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


print("Matrix 1 (using nested lists):")
for row in matrix1:
    print(row)

print("\nMatrix 2 (using list comprehension):")
for row in matrix2:
    print(row)

print("\nMatrix 3 (using NumPy):")
print(matrix3)


print("\nAccessing elements:")
print(f"Element at position [0][1] in matrix1: {matrix1[0][1]}")  # Should print 2
print(f"Element at position [1][2] in matrix1: {matrix1[1][2]}")  # Should print 6

matrix1[0][0] = 10
print("\nAfter modifying matrix1[0][0]:")
for row in matrix1:
    print(row)

Matrix 1 (using nested lists):
[1, 2, 3]
[4, 5, 6]

Matrix 2 (using list comprehension):
[0, 0, 0]
[0, 0, 0]

Matrix 3 (using NumPy):
[[1 2 3]
 [4 5 6]]

Accessing elements:
Element at position [0][1] in matrix1: 2
Element at position [1][2] in matrix1: 6

After modifying matrix1[0][0]:
[10, 2, 3]
[4, 5, 6]


In [11]:
import numpy as np

temperatures = [
    [75.2, 77.1, 74.5, 79.3, 82.6, 81.2, 77.8],
    [78, 88, 76, 75, 79, 70, 72]
]


temp_array = np.array(temperatures)

print("ndim:", temp_array.ndim)        
print("shape:", temp_array.shape)      
print("size:", temp_array.size)         
print("dtype:", temp_array.dtype)      
print("itemsize:", temp_array.itemsize) 

ndim: 2
shape: (2, 7)
size: 14
dtype: float64
itemsize: 8


In [14]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
add = np.add(a,b)
sub = np.subtract(a,b)
mul = np.multiply(a,b)
div = np.divide(a,b)
power = np.power(a,b)
print(add)
print(sub)
print(mul)
print(div)
print(power)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]


In [15]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
array.ndim

1

In [ ]:
array.ndim

1

In [18]:
import numpy as np


A = np.array([15, 25, 35, 45, 55])
B = np.array([5, 10, 15, 20, 25])


print("Addition:", A + B)
print("Subtraction:", A - B)
print("Multiplication:", A * B)
print("Division:", A / B)
print("Power:", A ** B)


C = np.array([12, 22, 32, 42, 52, 62, 72, 82, 92, 102])

print("\nMedian of C:", np.median(C))
print("Mean of C:", np.mean(C))
print("Standard Deviation of C:", np.std(C))
print("Variance of C:", np.var(C))


X = np.array(['Hello', 'Data', 'Science', 'Class', 'Learners'])
Y = np.array(['World', 'Analysis', 'is', 'Fun', '2023'])


concatenated = np.char.add(X, np.char.add(" ", Y))
print("Concatenated Strings:", concatenated)


X_upper = np.char.upper(X)
print("X in Uppercase:", X_upper)


Y_replaced = np.char.replace(Y, 'Fun', 'Enjoyment')
print("Y after replacement:", Y_replaced)

Addition: [20 35 50 65 80]
Subtraction: [10 15 20 25 30]
Multiplication: [  75  250  525  900 1375]
Division: [3.         2.5        2.33333333 2.25       2.2       ]
Power: [             759375      95367431640625 3351328013648404811
 6545036034076902481 6038590913291571831]

Median of C: 57.0
Mean of C: 57.0
Standard Deviation of C: 28.722813232690143
Variance of C: 825.0
Concatenated Strings: ['Hello World' 'Data Analysis' 'Science is' 'Class Fun' 'Learners 2023']
X in Uppercase: ['HELLO' 'DATA' 'SCIENCE' 'CLASS' 'LEARNERS']
Y after replacement: ['World' 'Analysis' 'is' 'Enjoyment' '2023']


In [19]:
import numpy as np


arr1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("1D Array:", arr1d)


arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
print("\n2D Array:\n", arr2d)


arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("\n3D Array:\n", arr3d)


print("\nAccessing with positive indices:")
print("1D: arr1d[2] =", arr1d[2])
print("2D: arr2d[1, 2] =", arr2d[1, 2])
print("3D: arr3d[1, 0, 2] =", arr3d[1, 0, 2])


add_result = arr1d[0] + arr2d[0, 0] + arr3d[0, 0, 0]
sub_result = arr1d[1] - arr2d[1, 1] - arr3d[1, 1, 1]
print("\nAddition of arr1d[0], arr2d[0,0], arr3d[0,0,0]:", add_result)
print("Subtraction of arr1d[1], arr2d[1,1], arr3d[1,1,1]:", sub_result)

print("\nAccessing with negative indices:")
print("1D: arr1d[-1] =", arr1d[-1])
print("2D: arr2d[-1, -2] =", arr2d[-1, -2])
print("3D: arr3d[-1, -1, -1] =", arr3d[-1, -1, -1])

1D Array: [ 10  20  30  40  50  60  70  80  90 100]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Accessing with positive indices:
1D: arr1d[2] = 30
2D: arr2d[1, 2] = 7
3D: arr3d[1, 0, 2] = 9

Addition of arr1d[0], arr2d[0,0], arr3d[0,0,0]: 12
Subtraction of arr1d[1], arr2d[1,1], arr3d[1,1,1]: 3

Accessing with negative indices:
1D: arr1d[-1] = 100
2D: arr2d[-1, -2] = 11
3D: arr3d[-1, -1, -1] = 12
