In [1]:
import numpy as np


arr_1d = np.arange(1, 16)
print("1D Array:\n", arr_1d)


arr_2d = np.arange(1, 21).reshape(4, 5)
print("\n2D Array:\n", arr_2d)


arr_3d = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D Array:\n", arr_3d)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [2]:

print("\nFirst 5 elements:", arr_1d[:5])
print("Elements from index 5 to 10:", arr_1d[5:11])
print("Every 2nd element:", arr_1d[::2])
print("Elements from index 3 to 12 with step 3:", arr_1d[3:13:3])


First 5 elements: [1 2 3 4 5]
Elements from index 5 to 10: [ 6  7  8  9 10 11]
Every 2nd element: [ 1  3  5  7  9 11 13 15]
Elements from index 3 to 12 with step 3: [ 4  7 10 13]


In [3]:

print("\nFirst 2 rows:\n", arr_2d[:2, :])


print("First 3 columns:\n", arr_2d[:, :3])


print("Rows 1-2 and columns 2-4:\n", arr_2d[1:3, 2:5])


First 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
First 3 columns:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
Rows 1-2 and columns 2-4:
 [[ 8  9 10]
 [13 14 15]]


In [4]:

print("\nFirst matrix:\n", arr_3d[0])


print("Second row of first matrix:\n", arr_3d[0, 1])

# Accessing the third element of the second row in the second matrix
print("Third element of second row in second matrix:", arr_3d[1, 1, 2])


First matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row of first matrix:
 [5 6 7 8]
Third element of second row in second matrix: 19


In [5]:
# 1D negative slicing
print("\nLast 5 elements (1D):", arr_1d[-5:])

# 2D negative slicing (last 2 rows, last 3 columns)
print("Last 2 rows and last 3 columns (2D):\n", arr_2d[-2:, -3:])

# 3D negative slicing (last matrix, last row, last 2 elements)
print("Last matrix, last row, last 2 elements (3D):", arr_3d[-1, -1, -2:])

# Compare with positive slicing
print("\nCompare negative and positive slicing (1D):")
print("Positive:", arr_1d[10:])
print("Negative:", arr_1d[-5:])


Last 5 elements (1D): [11 12 13 14 15]
Last 2 rows and last 3 columns (2D):
 [[13 14 15]
 [18 19 20]]
Last matrix, last row, last 2 elements (3D): [23 24]

Compare negative and positive slicing (1D):
Positive: [11 12 13 14 15]
Negative: [11 12 13 14 15]


In [6]:
# Exercise 1: Analyzing Carbon Emissions Data 
# Imagine you have a dataset containing carbon emissions from various cities in a country over a period of time. The data is organized in a NumPy array where each row represents a year, and each column represents a city. 
# Task: 
# 1. Create a 2D NumPy array that stores carbon emissions (in tons) for 5 cities over 10 years. The data should be random numbers between 1000 and 5000 (use numpy.random.randint). 
# 2. Find the total emissions for each city over the 10 years. 
# 3. Find the year with the highest total emissions. 
# 4. Calculate the average emissions for all cities in a specific year (say, Year 5).

# Step 1: Create a 2D NumPy array with random emissions data
import numpy as np
emissions_data = np.random.randint(1000, 5000, size=(10, 5))
print("\nCarbon Emissions Data (10 years, 5 cities):\n", emissions_data)
# Step 2: Find the total emissions for each city over the 10 years
total_emissions_per_city = emissions_data.sum(axis=0)
print("\nTotal emissions for each city over 10 years:", total_emissions_per_city)

# Step 3: Find the year with the highest total emissions
total_emissions_per_year = emissions_data.sum(axis=1)
highest_year_index = np.argmax(total_emissions_per_year)
highest_year = highest_year_index + 1  # Adding 1 to convert index to year (1-based)
print("Year with the highest total emissions:", highest_year)

# Step 4: Calculate the average emissions for all cities in Year 5
average_emissions_year_5 = emissions_data[4].mean()  # Year 5 is at index 4
print("Average emissions for all cities in Year 5:", average_emissions_year_5)


Carbon Emissions Data (10 years, 5 cities):
 [[1844 2317 2585 3046 4879]
 [4819 1665 4125 3076 1787]
 [3939 4541 1906 2539 1762]
 [4953 1243 1117 2076 4595]
 [2710 4243 4341 1155 3268]
 [1412 4876 3146 1930 1626]
 [4300 3463 2487 4899 1018]
 [4198 2844 2489 1916 1101]
 [4618 1152 3546 1119 1561]
 [1290 3425 2110 3916 1234]]

Total emissions for each city over 10 years: [34083 29769 27852 25672 22831]
Year with the highest total emissions: 7
Average emissions for all cities in Year 5: 3143.4


In [7]:
import numpy as np

# 1. Create a 2D NumPy array: 12 months (rows) x 5 fields (columns)
water_usage = np.random.randint(5000, 20000, size=(12, 5))
print("Water Usage Data (liters):\n", water_usage)

# 2. Calculate the total water usage for each field over the year
total_per_field = np.sum(water_usage, axis=0)
print("\nTotal water usage for each field over the year:", total_per_field)

# 3. Find the month with the highest water usage across all fields
total_per_month = np.sum(water_usage, axis=1)
max_month_index = np.argmax(total_per_month)
print("\nMonth with highest water usage (0=Jan, 11=Dec):", max_month_index)
print("Water usage in that month:", total_per_month[max_month_index])

# 4. Calculate the average water usage for all fields in a specific month (e.g., February, which is index 1)
feb_avg = np.mean(water_usage[1])
print("\nAverage water usage for all fields in February:", feb_avg)

Water Usage Data (liters):
 [[ 7351  6500 14812 15472  9592]
 [18687  9819  6214  8002 12533]
 [ 6352  7191  5570 16579 16500]
 [12087 19628 10253 11509 14321]
 [13026 19150 14567 18641  7771]
 [17664 18421 17368  7748 15503]
 [13655  9031  6908  7886 18934]
 [10084  5167 14933  5481 13392]
 [19460 19735 15385 13229 10553]
 [ 7425 13781 15177 13413 15421]
 [18441 18703 15914 12901 14184]
 [ 8547 18627  6583  8789  6051]]

Total water usage for each field over the year: [152779 165753 143684 139650 154755]

Month with highest water usage (0=Jan, 11=Dec): 10
Water usage in that month: 80143

Average water usage for all fields in February: 11051.0


In [10]:
import pandas as pd
# Sample Series
s = pd.Series([10, 20, 30, 40])

# Access element at index 2
element = s.iloc[2]
print("Element at index 2:", element)

Element at index 2: 30


In [12]:
i = [ 'a', 'b', 'c', 'd', 'e', 'f', 'g']
series_with_index = pd.Series(i, index = [1,2,3,4,5,6,7])
print(series_with_index)

#accessing elements
print(series_with_index[2])


#slicing
print(series_with_index[2:5])
print(series_with_index[:4])

1    a
2    b
3    c
4    d
5    e
6    f
7    g
dtype: object
b
3    c
4    d
5    e
dtype: object
1    a
2    b
3    c
4    d
dtype: object


In [14]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alu', 'Bobo', 'lulla', 'Da', 'Eva adams '],
    'Age': [25, 30, 35, 40, 28]
}
df = pd.DataFrame(data)

n = 2  # Number of rows you want


first_n = df.head(n)
print("First", n, "rows:\n", first_n)


last_n = df.tail(n)
print("\nLast", n, "rows:\n", last_n)

First 2 rows:
    Name  Age
0   Alu   25
1  Bobo   30

Last 2 rows:
          Name  Age
3          Da   40
4  Eva adams    28


In [16]:
import pandas as pd


temperatures = [30, 32, 31, 29, 28, 27, 26]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


temp_series = pd.Series(temperatures, index=days)


specific_days = temp_series[['Monday', 'Thursday']]
print("Temperature on Monday and Thursday:\n", specific_days)

total_temp = temp_series.sum()
print("\nTotal temperature for the week:", total_temp)

Temperature on Monday and Thursday:
 Monday      30
Thursday    29
dtype: int64

Total temperature for the week: 203


In [17]:
import pandas as pd


temperatures = [30, 32, 31, 29, 28, 27, 26]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']


temp_series = pd.Series(temperatures, index=days)


max_temp_day = temp_series.idxmax()
max_temp = temp_series.max()
print("Day with highest temperature:", max_temp_day, "(", max_temp, "°C )")


min_temp_day = temp_series.idxmin()
min_temp = temp_series.min()
print("Day with lowest temperature:", min_temp_day, "(", min_temp, "°C )")

Day with highest temperature: Tuesday ( 32 °C )
Day with lowest temperature: Sunday ( 26 °C )


In [18]:
import pandas as pd


temperatures = [30, 32, 31, 29, 28, 27, 26]
days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

temp_series = pd.Series(temperatures, index=days)


average_temp = temp_series.mean()
print("Average temperature for the week:", average_temp)

threshold = 2
significantly_different = temp_series[abs(temp_series - average_temp) > threshold]
print("\nDays with temperature significantly different from the average (>|2|°C):")
print(significantly_different)

Average temperature for the week: 29.0

Days with temperature significantly different from the average (>|2|°C):
Tuesday    32
Sunday     26
dtype: int64
