In [1]:
import numpy as np


arr_1d = np.arange(1, 16)
print("1D Array:\n", arr_1d)


arr_2d = np.arange(1, 21).reshape(4, 5)
print("\n2D Array:\n", arr_2d)


arr_3d = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D Array:\n", arr_3d)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [2]:

print("\nFirst 5 elements:", arr_1d[:5])
print("Elements from index 5 to 10:", arr_1d[5:11])
print("Every 2nd element:", arr_1d[::2])
print("Elements from index 3 to 12 with step 3:", arr_1d[3:13:3])


First 5 elements: [1 2 3 4 5]
Elements from index 5 to 10: [ 6  7  8  9 10 11]
Every 2nd element: [ 1  3  5  7  9 11 13 15]
Elements from index 3 to 12 with step 3: [ 4  7 10 13]


In [3]:

print("\nFirst 2 rows:\n", arr_2d[:2, :])


print("First 3 columns:\n", arr_2d[:, :3])


print("Rows 1-2 and columns 2-4:\n", arr_2d[1:3, 2:5])


First 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
First 3 columns:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
Rows 1-2 and columns 2-4:
 [[ 8  9 10]
 [13 14 15]]


In [4]:

print("\nFirst matrix:\n", arr_3d[0])


print("Second row of first matrix:\n", arr_3d[0, 1])

# Accessing the third element of the second row in the second matrix
print("Third element of second row in second matrix:", arr_3d[1, 1, 2])


First matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row of first matrix:
 [5 6 7 8]
Third element of second row in second matrix: 19


In [5]:
# 1D negative slicing
print("\nLast 5 elements (1D):", arr_1d[-5:])

# 2D negative slicing (last 2 rows, last 3 columns)
print("Last 2 rows and last 3 columns (2D):\n", arr_2d[-2:, -3:])

# 3D negative slicing (last matrix, last row, last 2 elements)
print("Last matrix, last row, last 2 elements (3D):", arr_3d[-1, -1, -2:])

# Compare with positive slicing
print("\nCompare negative and positive slicing (1D):")
print("Positive:", arr_1d[10:])
print("Negative:", arr_1d[-5:])


Last 5 elements (1D): [11 12 13 14 15]
Last 2 rows and last 3 columns (2D):
 [[13 14 15]
 [18 19 20]]
Last matrix, last row, last 2 elements (3D): [23 24]

Compare negative and positive slicing (1D):
Positive: [11 12 13 14 15]
Negative: [11 12 13 14 15]


In [6]:
# Exercise 1: Analyzing Carbon Emissions Data 
# Imagine you have a dataset containing carbon emissions from various cities in a country over a period of time. The data is organized in a NumPy array where each row represents a year, and each column represents a city. 
# Task: 
# 1. Create a 2D NumPy array that stores carbon emissions (in tons) for 5 cities over 10 years. The data should be random numbers between 1000 and 5000 (use numpy.random.randint). 
# 2. Find the total emissions for each city over the 10 years. 
# 3. Find the year with the highest total emissions. 
# 4. Calculate the average emissions for all cities in a specific year (say, Year 5).

# Step 1: Create a 2D NumPy array with random emissions data
import numpy as np
emissions_data = np.random.randint(1000, 5000, size=(10, 5))
print("\nCarbon Emissions Data (10 years, 5 cities):\n", emissions_data)
# Step 2: Find the total emissions for each city over the 10 years
total_emissions_per_city = emissions_data.sum(axis=0)
print("\nTotal emissions for each city over 10 years:", total_emissions_per_city)

# Step 3: Find the year with the highest total emissions
total_emissions_per_year = emissions_data.sum(axis=1)
highest_year_index = np.argmax(total_emissions_per_year)
highest_year = highest_year_index + 1  # Adding 1 to convert index to year (1-based)
print("Year with the highest total emissions:", highest_year)

# Step 4: Calculate the average emissions for all cities in Year 5
average_emissions_year_5 = emissions_data[4].mean()  # Year 5 is at index 4
print("Average emissions for all cities in Year 5:", average_emissions_year_5)


Carbon Emissions Data (10 years, 5 cities):
 [[1844 2317 2585 3046 4879]
 [4819 1665 4125 3076 1787]
 [3939 4541 1906 2539 1762]
 [4953 1243 1117 2076 4595]
 [2710 4243 4341 1155 3268]
 [1412 4876 3146 1930 1626]
 [4300 3463 2487 4899 1018]
 [4198 2844 2489 1916 1101]
 [4618 1152 3546 1119 1561]
 [1290 3425 2110 3916 1234]]

Total emissions for each city over 10 years: [34083 29769 27852 25672 22831]
Year with the highest total emissions: 7
Average emissions for all cities in Year 5: 3143.4
