In [1]:
import numpy as np


arr_1d = np.arange(1, 16)
print("1D Array:\n", arr_1d)


arr_2d = np.arange(1, 21).reshape(4, 5)
print("\n2D Array:\n", arr_2d)


arr_3d = np.arange(1, 25).reshape(2, 3, 4)
print("\n3D Array:\n", arr_3d)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [2]:

print("\nFirst 5 elements:", arr_1d[:5])
print("Elements from index 5 to 10:", arr_1d[5:11])
print("Every 2nd element:", arr_1d[::2])
print("Elements from index 3 to 12 with step 3:", arr_1d[3:13:3])


First 5 elements: [1 2 3 4 5]
Elements from index 5 to 10: [ 6  7  8  9 10 11]
Every 2nd element: [ 1  3  5  7  9 11 13 15]
Elements from index 3 to 12 with step 3: [ 4  7 10 13]


In [3]:

print("\nFirst 2 rows:\n", arr_2d[:2, :])


print("First 3 columns:\n", arr_2d[:, :3])


print("Rows 1-2 and columns 2-4:\n", arr_2d[1:3, 2:5])


First 2 rows:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
First 3 columns:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
Rows 1-2 and columns 2-4:
 [[ 8  9 10]
 [13 14 15]]


In [4]:

print("\nFirst matrix:\n", arr_3d[0])


print("Second row of first matrix:\n", arr_3d[0, 1])

# Accessing the third element of the second row in the second matrix
print("Third element of second row in second matrix:", arr_3d[1, 1, 2])


First matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row of first matrix:
 [5 6 7 8]
Third element of second row in second matrix: 19


In [5]:
# 1D negative slicing
print("\nLast 5 elements (1D):", arr_1d[-5:])

# 2D negative slicing (last 2 rows, last 3 columns)
print("Last 2 rows and last 3 columns (2D):\n", arr_2d[-2:, -3:])

# 3D negative slicing (last matrix, last row, last 2 elements)
print("Last matrix, last row, last 2 elements (3D):", arr_3d[-1, -1, -2:])

# Compare with positive slicing
print("\nCompare negative and positive slicing (1D):")
print("Positive:", arr_1d[10:])
print("Negative:", arr_1d[-5:])


Last 5 elements (1D): [11 12 13 14 15]
Last 2 rows and last 3 columns (2D):
 [[13 14 15]
 [18 19 20]]
Last matrix, last row, last 2 elements (3D): [23 24]

Compare negative and positive slicing (1D):
Positive: [11 12 13 14 15]
Negative: [11 12 13 14 15]
