In [1]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense 
import matplotlib.pyplot as plt 

In [2]:
np.random.seed(40)
data = np.random.randint(100,200, size =200)
data

array([170, 191, 107, 137, 156, 150, 165, 112, 171, 119, 131, 174, 155,
       183, 159, 191, 173, 196, 149, 153, 173, 108, 152, 130, 179, 114,
       192, 158, 174, 122, 103, 191, 199, 171, 155, 183, 128, 113, 137,
       182, 150, 179, 167, 130, 160, 144, 146, 187, 143, 135, 198, 131,
       182, 105, 180, 165, 107, 192, 141, 199, 195, 188, 193, 125, 183,
       158, 198, 170, 157, 157, 183, 185, 136, 163, 174, 188, 100, 101,
       133, 152, 172, 157, 134, 114, 178, 171, 156, 177, 186, 184, 182,
       191, 112, 190, 173, 127, 100, 121, 194, 132, 151, 150, 120, 141,
       178, 155, 147, 143, 191, 176, 129, 145, 107, 110, 161, 119, 168,
       125, 161, 198, 116, 188, 161, 151, 188, 141, 158, 121, 131, 195,
       143, 168, 116, 103, 115, 179, 104, 106, 194, 166, 185, 151, 190,
       183, 102, 109, 106, 139, 125, 156, 117, 113, 107, 150, 196, 148,
       153, 100, 138, 160, 148, 167, 197, 161, 145, 161, 110, 177, 157,
       152, 140, 101, 152, 158, 188, 122, 148, 124, 158, 193, 17

In [3]:
#prepare input sequences (x = past 7 days)
#labels y = next day
def prepare_data(data, sequence_length = 7):
    x, y = [], []
    for i in range(len(data) - sequence_length):
        x.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length])
    return np.array(x), np.array(y)

In [4]:
X, y = prepare_data(data)

In [5]:
X

array([[170, 191, 107, ..., 156, 150, 165],
       [191, 107, 137, ..., 150, 165, 112],
       [107, 137, 156, ..., 165, 112, 171],
       ...,
       [196, 102, 164, ..., 179, 194, 110],
       [102, 164, 175, ..., 194, 110, 115],
       [164, 175, 179, ..., 110, 115, 197]])

In [6]:
y

array([112, 171, 119, 131, 174, 155, 183, 159, 191, 173, 196, 149, 153,
       173, 108, 152, 130, 179, 114, 192, 158, 174, 122, 103, 191, 199,
       171, 155, 183, 128, 113, 137, 182, 150, 179, 167, 130, 160, 144,
       146, 187, 143, 135, 198, 131, 182, 105, 180, 165, 107, 192, 141,
       199, 195, 188, 193, 125, 183, 158, 198, 170, 157, 157, 183, 185,
       136, 163, 174, 188, 100, 101, 133, 152, 172, 157, 134, 114, 178,
       171, 156, 177, 186, 184, 182, 191, 112, 190, 173, 127, 100, 121,
       194, 132, 151, 150, 120, 141, 178, 155, 147, 143, 191, 176, 129,
       145, 107, 110, 161, 119, 168, 125, 161, 198, 116, 188, 161, 151,
       188, 141, 158, 121, 131, 195, 143, 168, 116, 103, 115, 179, 104,
       106, 194, 166, 185, 151, 190, 183, 102, 109, 106, 139, 125, 156,
       117, 113, 107, 150, 196, 148, 153, 100, 138, 160, 148, 167, 197,
       161, 145, 161, 110, 177, 157, 152, 140, 101, 152, 158, 188, 122,
       148, 124, 158, 193, 174, 189, 196, 143, 164, 171, 106, 14

In [7]:
X = X.reshape((X.shape[0], X.shape[1], 1))  # Reshape for RNN input
X.shape

(193, 7, 1)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
#build the RNN model
rnnmodel = Sequential()
rnnmodel.add(SimpleRNN(50, activation='relu', input_shape=(X_train.shape[1], 1)))
rnnmodel.add(Dense(1))  # Output layer for regression

rnnmodel.compile(optimizer='adam', loss='mse')
#train the model
history = rnnmodel.fit(X_train, y_train, epochs=30, verbose=1)

2025-06-17 15:02:19.585340: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2
2025-06-17 15:02:19.585603: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-06-17 15:02:19.585607: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-06-17 15:02:19.585650: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-06-17 15:02:19.585703: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefe

Epoch 1/30


2025-06-17 15:02:20.556567: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 168ms/step - loss: 23039.0820
Epoch 2/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 17733.2031
Epoch 3/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 13800.2236
Epoch 4/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 8911.1650
Epoch 5/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 5845.0420
Epoch 6/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 2341.9033
Epoch 7/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1257.9183
Epoch 8/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1751.8156
Epoch 9/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1201.5608
Epoch 10/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1087.7361
Epoch 11/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1187.6016
Epoch 12/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1027.1937
Epoch 13/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 918.2195
Epoch 14/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1008.0411
Epoch 15/30
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 994.979

In [10]:
y_pred  = rnnmodel.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 356ms/step


In [11]:
X_test.shape

(39, 7, 1)

In [18]:
new_data = [160,200,180,170,190,210,220]
new_prediction = rnnmodel.predict(np.array(new_data).reshape(1, 7, 1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


In [21]:
new_prediction

array([[198.81319]], dtype=float32)

In [22]:
X_test[1]

array([[106],
       [194],
       [166],
       [185],
       [151],
       [190],
       [183]])

In [23]:
y_test[1]

102

In [24]:
rnnmodel.predict(X_test[1].reshape(1, 7, 1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[173.69606]], dtype=float32)